language: node_js
node_js:
  - "stable"
install: npm install
script: npm run-script build
jobs:
  include:
    - stage: deploy
      script: bash ./travis/deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
cache:
  directories:
    - node_modules
notifications:
  email: false