language: node_js
node_js:
  - "stable"
install: npm install
jobs:
  include:
    - stage: deploy
      script: bash ./travis/deploy.sh
cache:
  directories:
    - node_modules
notifications:
  email: false